export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  DASHBOARD: '/dashboard',
  TOOLS: '/tools',
  TOOL_CHECKOUT: '/tool-checkout',
  TOOL_HISTORY: '/tool-history',
  CHEMICALS: '/chemicals',
  KITS: '/kits',
  WAREHOUSES: '/warehouses',
  TRANSFERS: '/transfers',
  REPORTS: '/reports',
  USERS: '/users',
  ADMIN: '/admin',
  PROFILE: '/profile',
  SETTINGS: '/settings',
  CHEMICAL_FORECAST: '/chemicals/forecast',
} as const;
