export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  DASHBOARD: '/dashboard',
  TOOLS: '/tools',
  TOOL_CHECKOUT: '/tool-checkout',
  TOOL_HISTORY: '/tool-history',
  CHEMICALS: '/chemicals',
  KITS: '/kits',
  MASTER_KITS: '/admin/master-kits',
  WAREHOUSES: '/warehouses',
  TRANSFERS: '/transfers',
  REPORTS: '/reports',
  ADMIN: '/admin',
  PROFILE: '/profile',
  SETTINGS: '/settings',
  CHEMICAL_FORECAST: '/chemicals/forecast',
  DISPLAY: '/display',
  ONCALL_SCHEDULE: '/oncall',
} as const;
